{
 "title": "City Mood Map",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "City Mood",
   "type": "geomap",
   "description": "Displays City Mood Value for Hamburg",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT \n    c.name, \n    c.latitude AS latitude, \n    c.longitude AS longitude, \n    cms.city_mood_score\nFROM cities c\nCROSS JOIN (\n    SELECT *\n    FROM city_mood_scores\n    ORDER BY window_start DESC\n    LIMIT 1\n) cms;\n"
    }
   ]
  },
  {
   "title": "City Mood Score",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT window_start, city_mood_score FROM city_mood_scores ORDER BY window_start LIMIT 50 "
    }
   ]
  },
  {
   "title": "City Mode Score - Components",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT city_mood_score, window_start, news_score, air_score, weather_score, traffic_score, alerts_score, construction_score, water_score FROM city_mood_scores ORDER BY window_start LIMIT 50 "
    }
   ]
  },
  {
   "title": "City Mood Score History - Spark Batches",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT city_mood_score, computed_at FROM city_mood_score_history ORDER BY window_end DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of used Datapoints",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT\n  window_end,\n  total_data_points\nFROM city_mood_scores\nORDER BY window_end ASC\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "City Mood Score Component History - Spark Batches",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "-- In Grafana Datasource Query:\nSELECT \n    written_at as time,\n    city_mood_score,\n    news_score,\n    air_score,\n    weather_score,\n    traffic_score,\n    alerts_score,\n    construction_score,\n    water_score\nFROM city_mood_score_history\nWHERE $__timeFilter(written_at)\nORDER BY written_at DESC"
    }
   ]
  },
  {
   "title": "Highest City Mood Score ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT MAX(city_mood_score) FROM city_mood_scores LIMIT 50 "
    }
   ]
  },
  {
   "title": "Lowest City Mood Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT MIN(city_mood_score) FROM city_mood_scores LIMIT 50 "
    }
   ]
  },
  {
   "title": "Total Number of City Mood Scores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 55 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT COUNT(city_mood_score) FROM city_mood_scores LIMIT 50 "
    }
   ]
  },
  {
   "title": "Validation Success Rate",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT\n  CASE\n    WHEN validation_success IS TRUE  THEN 'true'\n    WHEN validation_success IS FALSE THEN 'false'\n    ELSE 'null'\n  END AS label,\n  ROUND(\n    COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (),\n    2\n  ) AS value\nFROM city_mood_score_history\nWHERE computed_at IS NOT NULL\n  AND $__timeFilter(computed_at)\nGROUP BY label\nORDER BY label;\n"
    }
   ]
  },
  {
   "title": "List of Warnings during Validation",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 59 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT\n  computed_at,\n  validation_warnings_list\nFROM city_mood_score_history\nWHERE validation_warnings_list IS NOT NULL\n  AND validation_warnings_list <> '[]'\nORDER BY computed_at DESC\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "List of Errors during Validation",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 59 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT\n  computed_at,\n  validation_failed_list\nFROM city_mood_score_history\nWHERE validation_failed_list IS NOT NULL\n  AND validation_failed_list <> '[]'\nORDER BY computed_at DESC\nLIMIT 50;\n"
    }
   ]
  },
  {
   "title": "Validation Expectations - Batches",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 66 },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT validation_evaluated_expectations, validation_successful_expectations, computed_at FROM city_mood_score_history LIMIT 100"
    }
   ]
  },
  {
   "title": "Number of calculated batches",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 66 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "city_mood",
     "rawSql": "SELECT COUNT(id) FROM city_mood_score_history LIMIT 50 "
    }
   ]
  }
 ]
}